package com.khaldi.biblo.ui

data class Book(
    val title : String? = null,
    val author : String? =null ,
    val description : String? = null,
    val image : String? = null
)

fun getLisBook() = listOf(

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),

 Book(title = "Modern C++ Programming Cookbook",author = "Marius Bancila",description = "C++ has come a long way to be one of the most widely used general-purpose languages that is fast, efficient, and high-performance at its core.\n" +
         "\n" +
         "The updated second edition of Modern C++ Programming Cookbook addresses the latest features of C++20, such as modules, concepts, coroutines, and the many additions to the standard library, including ranges and text formatting. The book is organized in the form of practical recipes covering a wide range of problems faced by modern developers.\n" +
         "\n" +
         "The book also delves into the details of all the core concepts in modern C++ programming, such as functions and classes, iterators and algorithms, streams and the file system, threading and concurrency, smart pointers and move semantics, and many others. It goes into the performance aspects of programming in depth, teaching developers how to write fast and lean code with the help of best practices.\n" +
         "\n" +
         "Furthermore, the book explores useful patterns and delves into the implementation of many idioms, including pimpl, named parameter, and attorney-client, teaching techniques such as avoiding repetition with the factory pattern. There is also a chapter dedicated to unit testing, where you are introduced to three of the most widely used libraries for C++: Boost.Test, Google Test, and Catch2.\n" +
         "\n" +
         "By the end of the book, you will be able to effectively leverage the features and techniques of C++11/14/17/20 programming to enhance the performance, scalability, and efficiency of your applications.",image = "https://images-na.ssl-images-amazon.com/images/P/1800208987.08.LZZZZZZZ.jpg")
 ,

 Book(title = "C++ en action",author = "Christopher Diggins",description = "++ est un langage riche et complexe, aux puissantes fonctionnalités : bâti autour du langage C, il est orienté objet et propose des fonctions en ligne, la surcharge d'opérateurs, etc. Il se retrouve aujourd'hui à la base de nombreux applicatifs et d'interfaces de développement graphiques. Cet ouvrage propose un ensemble de 171 solutions adaptables immédiatement sur le modèle : un problème, une solution, une discussion. Des experts en C++ répondent ici aux questions que tout programmeur en C++ se pose un jour ou l'autre. L'accent a été mis d'une part sur la performance et sur la portabilité et d'autre part sur le recours aux nombreuses bibliothèques C++ et notamment Boost. Les recettes proposées couvrent un large éventail de domaines, allant des tâches simples à des manipulations plus complexes ; vous trouverez par exemple : Travailler avec des nombres pour les convertir, les comparer. Dates et heures : formatage, conversion, etc. Gestion des exceptions et sécurité : créer une classe exception. Classes et objets : initialiser des variables membres de classe, appeler une fonction virtuelle d'une super-classe. Construire des applications C++ avec make, Boost. Build. Analyser du XML et utiliser les Schemas, XSLT, XPath. Manipuler des chaînes de caractères et du texte. Le multithreading : créer un thread, initialiser une seule fois une ressource partagée, etc. L'internationalisation : lire et écrire des devises, des dates, saisir une chaîne Unicode. Calculs mathématiques et scientifiques : somme, moyenne, statistiques, distance entre deux vecteurs. Les algorithmes : retirer des objets d'un conteneur, ordonner un intervalle. S'il est parfois instructif de réinventer la roue, le faire en C++ n'apportera que désagréments et perte de temps. Recourir à la bibliothèque standard de C++, aux bibliothèques Boost et aux solutions proposées ici feront gagner un temps précieux au programmeur et lui épargneront des lignes de codes inutiles, qu'il soit débutant ou plus expérimenté.",image = "https://images-na.ssl-images-amazon.com/images/P/2841774074.08.LZZZZZZZ.jpg"),

 Book(title = "Programmation Python avancée",author = "Xavier Olive",description = "Ce livre s’adresse à des lecteurs ayant déjà une certaine expérience de la programmation. Son objectif est de rappeler les concepts-clés de Python et de les illustrer dans des cas d’utilisation variés comme l’optimisation, les",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100815982-001-X.jpeg"),
 Book(title = "Programmer avec Kotlin",author = "Josh Skeen",description = "otlin est un langage de programmation orienté objet conçu principalement par une équipe de programmeurs chez JetBrains basée en Russie (son nom vient de l'île de Kotline, près de St. Petersbourg). Google a annoncé en 2017 que Kotlin.",image = "https://www.dunod.com/sites/default/files/styles/principal_desktop/public/thumbnails/image/9782100810994-001-X.jpeg"),



 )